# GNU_INSTALL_ROOT := C:/Program Files (x86)/GNU Tools ARM Embedded/9 2019-q4-major/bin/
# GNU_VERSION := 9.2.1
# GNU_PREFIX := arm-none-eabi
GNU_INSTALL_ROOT := C:/ST/STM32CubeIDE_1.1.0/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-arm-embedded.7-2018-q2-update.win32_1.0.0.201904081647/tools/bin/
GNU_VERSION := 7.3.1
GNU_PREFIX := arm-none-eabi
